name: rosa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  # Menambahkan dependensi flutter_launcher_icons
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/rosa.png  # Pastikan gambar ikon Anda ada di sini

# Menambahkan konfigurasi flutter_icons di luar bagian flutter
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png  # Ganti dengan lokasi gambar ikon Anda
